name: Build image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_USERNAME: gitea
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: export
        run: |
          bun install @react-native/assets-registry @babel/runtime react-native-root-siblings expo-asset babel-preset-expo
          npx expo export --platform web
      
      - name: Login to gitea Container Registry
        uses: docker/login-action@v3
        with:
          username: schoolwarenext
          password: ${{ secrets.DOCKER_HUB  }}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64                                                
          push: true
          tags: schoolwarenext/schoolware-frontend:latest
