name: Build image
on:
  [push]
jobs:
  build-image:
    runs-on: android
    container:
      volumes:
          - /android:/android
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build
        run: |
          pnpm install @react-native/assets-registry
          pnpm i expo-asset
          pnpm i babel-preset-expo
          pnpm i @babel/runtime

          ANDROID_HOME=/android/Sdk PATH=$PATH:$ANDROID_HOME/emulator PATH=$PATH:$ANDROID_HOME/platform-tools npx react-native build-android --verbose --tasks assemble

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: release apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk 
      
      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: debug apk
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            


