name: Build image
on:
  [push]
jobs:
  build-image:
    runs-on: android
    container:
      volumes:
          - /android:/android
          - /home/mb/schoolware-frontend:/root/.gradle

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
#          cache: gradle

      - name: Build
        run: |
          ANDROID_HOME=/android/Sdk PATH=$PATH:$ANDROID_HOME/emulator PATH=$PATH:$ANDROID_HOME/platform-tools npx react-native build-android --verbose --tasks assemble

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: release apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk 
      
      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: debug apk
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            - uses: actions/checkout@v2

 #     - name: Release local
 #       uses: softprops/action-gh-release@v2
 #       token: ${{ secrets.gitea  }}
 #       with:
 #         files: |
 #           android/app/build/outputs/apk/release/app-release.apk 
 #           android/app/build/outputs/apk/debug/app-debug.apk
      
      - name: Release githhub
        uses: softprops/action-gh-release@v2
        token: ${{ secrets.github  }}
        repository: schoolware-nextgen/schoolware-frontend
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            android/app/build/outputs/apk/release/app-release.apk 
            android/app/build/outputs/apk/debug/app-debug.apk
            


