name: Build image
on:
  [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_USERNAME: gitea
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - name: install and export
        run: |
          npm config set fetch-retries 4
          npm config set fetch-retry-mintimeout 100000
          npm i
          npx expo export --platform web
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64                                                
          push: true
          tags: git.mb-server.com/mb/schoolware-frontend:latest
          password: ${{ secrets.DOCKER_TOKEN }}